package ec.edu.espe.crealtivastudios.view;
import com.mongodb.client.*;
import com.mongodb.client.model.Filters;
import com.mongodb.client.model.Updates;
import utils.*; 
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.bson.Document;
/**
 *
 * @author Kevin Chalan, OBJECT MASTER, OOP
 */
public class FrmAssignEvent extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmAssignEvent.class.getName());
// Modelos para controlar la Tabla y los ComboBox
    DefaultTableModel tableModel = new DefaultTableModel();
    DefaultComboBoxModel<String> comboPhotographersModel = new DefaultComboBoxModel<>();
    DefaultComboBoxModel<String> comboEventsModel = new DefaultComboBoxModel<>();
    
    /**
     * Creates new form FrmAssignEvent
     */
    public FrmAssignEvent() {
initComponents();
        this.setLocationRelativeTo(null); 

        try {

            MongoConnection.connect(); 
        } catch (Exception e) {
            System.out.println("Error de conexión: " + e.getMessage());
        }
        
        setupTable(); 
        loadData();
    }
    

    
    private void loadData() {
      
        loadEvents(); 
        loadAvailablePhotographers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboPhotographer = new javax.swing.JComboBox<>();
        jComboEvent = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        btnQuitAssign = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.SystemColor.activeCaption);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        jPanel2.setBackground(java.awt.SystemColor.activeCaption);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel1.setText("ASIGNAR EVENTO A FOTOGRAFO");

        jComboPhotographer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboPhotographer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboPhotographerActionPerformed(evt);
            }
        });

        jComboEvent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboEventActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("Fotografo");

        jLabel3.setText("Evento");

        jToggleButton1.setText("Guardar");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToggleButton2.setText("Salir");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        btnQuitAssign.setText("Quitar Asignacion");
        btnQuitAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitAssignActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jComboPhotographer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboEvent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnQuitAssign)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(10, 10, 10)
                        .addComponent(jComboPhotographer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboEvent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1)
                    .addComponent(jToggleButton2)
                    .addComponent(btnQuitAssign))
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
    FrmCrealtivaStudiosMenu frmCrealtivaStudiosMenu = new FrmCrealtivaStudiosMenu();
 frmCrealtivaStudiosMenu.setVisible(true);
this.setVisible(false);    
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
if (jComboPhotographer.getSelectedIndex() <= 0) {
            JOptionPane.showMessageDialog(this, "Seleccione un fotógrafo.");
            jToggleButton1.setSelected(false);
            return;
        }
        if (jComboEvent.getSelectedIndex() <= 0) {
            JOptionPane.showMessageDialog(this, "Seleccione un evento.");
            jToggleButton1.setSelected(false);
            return;
        }

        String photogName = (String) jComboPhotographer.getSelectedItem();
        String eventName = (String) jComboEvent.getSelectedItem();

        try {
            MongoDatabase db = MongoDBConnection.getConnection();
            
          
            MongoCollection<Document> photoColl = db.getCollection("PhotographerDB");
            photoColl.updateOne(
                Filters.eq("name", photogName),
                Updates.combine(
                    Updates.set("assigned", true),
                    Updates.set("assignedEvent", eventName)
                )
            );
            
         
            MongoCollection<Document> eventColl = db.getCollection("Events");
            

            eventColl.updateOne(
                Filters.eq("eventName", eventName), 
                Updates.set("assignedPhotographer", photogName)
            );


            JOptionPane.showMessageDialog(this, "Asignación exitosa: " + photogName + " -> " + eventName);
            loadData();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
        
        jToggleButton1.setSelected(false);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jComboEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboEventActionPerformed

    }//GEN-LAST:event_jComboEventActionPerformed

    private void jComboPhotographerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboPhotographerActionPerformed

    }//GEN-LAST:event_jComboPhotographerActionPerformed

    private void btnQuitAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitAssignActionPerformed

        int selectedRow = jTable1.getSelectedRow();
        
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona un evento de la tabla para borrar su asignación.");
            return;
        }

   
        String eventName = jTable1.getValueAt(selectedRow, 1).toString();
        String assignedTo = jTable1.getValueAt(selectedRow, 2).toString();


        if (assignedTo.equals("NO ASIGNADO")) {
            JOptionPane.showMessageDialog(this, "Este evento no tiene fotógrafo asignado.");
            return;
        }


        int confirm = JOptionPane.showConfirmDialog(this, 
                "¿Estás seguro de quitar a " + assignedTo + " del evento " + eventName + "?",
                "Borrar Asignación", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            try {
                MongoDatabase db = MongoConnection.getDatabase();
                
                MongoCollection<Document> eventColl = db.getCollection("Events");
                eventColl.updateOne(
                    Filters.eq("eventName", eventName),
                    Updates.set("assignedPhotographer", "") // Borramos el nombre
                );


                MongoCollection<Document> photoColl = db.getCollection("PhotographerDB");
                photoColl.updateOne(
                    Filters.eq("name", assignedTo),
                    Updates.combine(
                        Updates.set("assigned", false),
                        Updates.set("assignedEvent", "")
                    )
                );

                JOptionPane.showMessageDialog(this, "Asignación eliminada correctamente.");
                
                loadData();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al borrar: " + e.getMessage());
            }
        }        
    }//GEN-LAST:event_btnQuitAssignActionPerformed

    private void setupTable() {

        String[] columns = {"ID Evento", "Nombre Evento", "Asignado A"};
        tableModel.setColumnIdentifiers(columns);
        jTable1.setModel(tableModel);

        jComboPhotographer.setModel(comboPhotographersModel);
        jComboEvent.setModel(comboEventsModel);
    }

    private void loadEvents() {
try {
            MongoDatabase db = MongoDBConnection.getConnection();
            MongoCollection<Document> eventsColl = db.getCollection("Events");
            
            tableModel.setRowCount(0); 
            comboEventsModel.removeAllElements();
            comboEventsModel.addElement("- Seleccione Evento -");
            
            for (Document doc : eventsColl.find()) {
                int id = doc.getInteger("eventId", 0);
                
                String name = doc.getString("eventName"); 
                
                String assignedPhotographer = doc.getString("assignedPhotographer");
                String statusText = "NO ASIGNADO";
                
                if (assignedPhotographer != null && !assignedPhotographer.isEmpty()) {
                    statusText = assignedPhotographer; 
                }

                tableModel.addRow(new Object[]{id, name, statusText});

                if (name != null) {
                    comboEventsModel.addElement(name);
                }
            }
        } catch (Exception e) {
            System.out.println("Error cargando eventos: " + e.getMessage());
        }
    }

    private void loadAvailablePhotographers() {
        try {
            MongoCollection<Document> photoColl = MongoConnection.getPhotographerCollection();
            
            comboPhotographersModel.removeAllElements();
            comboPhotographersModel.addElement("- Seleccione Fotógrafo -");
 
            for (Document doc : photoColl.find(Filters.eq("assigned", false))) {
                String name = doc.getString("name");
                comboPhotographersModel.addElement(name);
            }
        } catch (Exception e) {
            System.out.println("Error cargando fotógrafos: " + e.getMessage());
        }
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmAssignEvent().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuitAssign;
    private javax.swing.JComboBox<String> jComboEvent;
    private javax.swing.JComboBox<String> jComboPhotographer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables
}
