package ec.edu.espe.crealtivastudios.view;

import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import com.mongodb.client.model.Filters;
import utils.MongoDBConnection;

// Importaciones necesarias para el reporte
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;  // <--- Esta es vital para leer los equipos
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.bson.Document;
/**
 *
 * @author Kevin Chalan, OBJECT MASTER, OOP
 */
public class FrmReportEvent extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmReportEvent.class.getName());

    /**
     * Creates new form FrmReportEvent
     */
    DefaultTableModel tableModel = new DefaultTableModel();
    public FrmReportEvent() {
       initComponents();
        this.setLocationRelativeTo(null); // Centrar ventana
        
        // 1. Conectar a Mongo al abrir
        try {
            MongoDBConnection.getConnection();
        } catch (Exception e) {
            System.out.println("Error conexión: " + e.getMessage());
        }
        
        // 2. Configurar columnas y cargar datos
        setupTable();
        loadReportData();
    }
    
    // Configuración de las columnas del reporte
    private void setupTable() {
        String[] columns = {
            "Fotógrafo", 
            "Evento Asignado", 
            "Fecha Evento", 
            "Tipo Evento", 
            "Equipos que lleva"
        };
        tableModel.setColumnIdentifiers(columns);
        jTable1.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButtonSaveReportInMongo = new javax.swing.JButton();
        jButtonPrint = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBackground(java.awt.SystemColor.activeCaption);

        jButtonSaveReportInMongo.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButtonSaveReportInMongo.setText("Guardar");
        jButtonSaveReportInMongo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveReportInMongoActionPerformed(evt);
            }
        });

        jButtonPrint.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButtonPrint.setText("Imprimir");
        jButtonPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrintActionPerformed(evt);
            }
        });

        jButtonExit.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButtonExit.setText("Salir");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jButtonSaveReportInMongo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSaveReportInMongo)
                    .addComponent(jButtonPrint)
                    .addComponent(jButtonExit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(java.awt.SystemColor.activeCaption);

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel1.setText("REPORTE DEL EVENTO ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrintActionPerformed
// En lugar de imprimir, generamos un documento HTML elegante
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Guardar Reporte PDF/HTML");
        
        int userSelection = fileChooser.showSaveDialog(this);
        
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();
            if (!fileToSave.getAbsolutePath().endsWith(".html")) {
                fileToSave = new File(fileToSave.getAbsolutePath() + ".html");
            }
            
            try (BufferedWriter bw = new BufferedWriter(new FileWriter(fileToSave, java.nio.charset.StandardCharsets.UTF_8))) {
                // Escribir estructura HTML con estilos CSS para que se vea BONITO
                bw.write("<html><head><title>Reporte CreAltiva</title>");
                bw.write("<style>");
                bw.write("body { font-family: Arial, sans-serif; margin: 40px; }");
                bw.write("h1 { color: #333; text-align: center; }");
                bw.write("table { width: 100%; border-collapse: collapse; margin-top: 20px; }");
                bw.write("th, td { border: 1px solid #ddd; padding: 12px; text-align: left; }");
                bw.write("th { background-color: #007bff; color: white; }"); // Cabecera azul
                bw.write("tr:nth-child(even) { background-color: #f2f2f2; }"); // Filas alternas grises
                bw.write("</style></head><body>");
                
                bw.write("<h1>Reporte de Asignaciones y Equipos</h1>");
                bw.write("<h3>CreAltiva Studios - " + new java.util.Date() + "</h3>");
                
                bw.write("<table>");
                
                // Cabeceras
                bw.write("<thead><tr>");
                for (int i = 0; i < jTable1.getColumnCount(); i++) {
                    bw.write("<th>" + jTable1.getColumnName(i) + "</th>");
                }
                bw.write("</tr></thead>");
                
                // Datos
                bw.write("<tbody>");
                for (int i = 0; i < jTable1.getRowCount(); i++) {
                    bw.write("<tr>");
                    for (int j = 0; j < jTable1.getColumnCount(); j++) {
                        Object val = jTable1.getValueAt(i, j);
                        String strVal = (val == null) ? "" : val.toString();
                        bw.write("<td>" + strVal + "</td>");
                    }
                    bw.write("</tr>");
                }
                bw.write("</tbody></table>");
                bw.write("</body></html>");
                
                JOptionPane.showMessageDialog(this, "Documento generado correctamente.\nÁbrelo con tu navegador.");
                
                // Opcional: Abrir el archivo automáticamente
                java.awt.Desktop.getDesktop().open(fileToSave);
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error generando documento: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_jButtonPrintActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
FrmCrealtivaStudiosMenu menu = new FrmCrealtivaStudiosMenu();
        menu.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonSaveReportInMongoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveReportInMongoActionPerformed
   JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Guardar Reporte Excel/CSV");
        
        int userSelection = fileChooser.showSaveDialog(this);
        
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();
            if (!fileToSave.getAbsolutePath().endsWith(".csv")) {
                fileToSave = new File(fileToSave.getAbsolutePath() + ".csv");
            }
            
            try (BufferedWriter bw = new BufferedWriter(new FileWriter(fileToSave, java.nio.charset.StandardCharsets.UTF_8))) {
                // 1. IMPORTANTE: Escribir BOM para que Excel reconozca tildes/ñ
                bw.write("\uFEFF");
                
                // 2. Títulos (Separados por PUNTO Y COMA para Excel en español)
                for (int i = 0; i < jTable1.getColumnCount(); i++) {
                    bw.write(jTable1.getColumnName(i));
                    if (i < jTable1.getColumnCount() - 1) bw.write(";"); // USAR ;
                }
                bw.newLine();
                
                // 3. Datos
                for (int i = 0; i < jTable1.getRowCount(); i++) {
                    for (int j = 0; j < jTable1.getColumnCount(); j++) {
                        Object val = jTable1.getValueAt(i, j);
                        String strVal = (val == null) ? "" : val.toString();
                        
                        // Limpiar saltos de línea y comillas dobles
                        strVal = strVal.replace("\"", "\"\"");
                        strVal = strVal.replace("\n", " ");
                        
                        // Encerramos en comillas por seguridad
                        bw.write("\"" + strVal + "\"");
                        
                        if (j < jTable1.getColumnCount() - 1) bw.write(";"); // USAR ;
                    }
                    bw.newLine();
                }
                
                JOptionPane.showMessageDialog(this, "Reporte guardado. \nÁbrelo en Excel y se verá ordenado.");
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error guardando: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_jButtonSaveReportInMongoActionPerformed
// --- LÓGICA DE CARGA DE DATOS (JOIN MANUAL) ---
    private void loadReportData() {
try {
            MongoDatabase db = MongoDBConnection.getConnection();
            MongoCollection<Document> photoColl = db.getCollection("PhotographerDB");
            MongoCollection<Document> eventColl = db.getCollection("Events");
            
            // Limpiar la tabla antes de cargar
            tableModel.setRowCount(0); 
            
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd"); // Formato de fecha

            // Recorremos CADA fotógrafo
            for (Document photoDoc : photoColl.find()) {
                // 1. Datos del Fotógrafo
                String photoName = photoDoc.getString("name");
                String eventName = photoDoc.getString("assignedEvent");
                boolean isAssigned = photoDoc.getBoolean("assigned", false);
                
                // Valores por defecto
                String dateStr = "---";
                String typeStr = "---";
                String equipStr = "Ninguno";
                
                // 2. Si tiene evento, buscamos los detalles en la colección 'Events'
                if (isAssigned && eventName != null && !eventName.isEmpty() && !eventName.equals("Bloqueado por disponibilidad")) {
                    Document eventDoc = eventColl.find(Filters.eq("eventName", eventName)).first();
                    
                    if (eventDoc != null) {
                        Date date = eventDoc.getDate("date");
                        if (date != null) dateStr = dateFormat.format(date);
                        typeStr = eventDoc.getString("eventType");
                    }
                } else {
                    eventName = "DISPONIBLE";
                }

                // 3. LEER EQUIPOS (CORRECCIÓN CRÍTICA AQUÍ)
                try {
                    // Mongo devuelve un ArrayList<String>, lo convertimos a texto
                    List<String> equipmentList = (List<String>) photoDoc.get("equipment");
                    
                    if (equipmentList != null && !equipmentList.isEmpty()) {
                        // Unimos la lista con comas: "Cámara, Luz, Trípode"
                        equipStr = String.join(", ", equipmentList);
                    }
                } catch (Exception ex) {
                    equipStr = "Error formato equipos";
                }

                // 4. Agregar la fila a la tabla
                tableModel.addRow(new Object[]{
                    photoName, 
                    eventName, 
                    dateStr, 
                    typeStr, 
                    equipStr
                });
            }
            
        } catch (Exception e) {
            System.out.println("Error en el reporte: " + e.getMessage());
            e.printStackTrace();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmReportEvent().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonPrint;
    private javax.swing.JButton jButtonSaveReportInMongo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
