package ec.edu.espe.crealtivastudios.view;

import ec.edu.espe.crealtivastudios.controller.UserController;
import ec.edu.espe.crealtivastudios.model.User;
import ec.edu.espe.crealtivastudios.view.FrmCrealtivaStudiosMenu;
import java.awt.Color;
import java.awt.Image;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.UIManager;

/**
 *
 * @author Kevin Chalan, OBJECT MASTER, OOP
 */
public class FrmCrealtivaStudiosLogin extends javax.swing.JFrame {
    
    

    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmCrealtivaStudiosLogin.class.getName());

    /**
     * Creates new form FrmCrealtivaStudiosLogin
     */
    public FrmCrealtivaStudiosLogin() {
   initComponents();

    getContentPane().setBackground(new Color(18, 18, 18));

    // Campos oscuros
    txtUser.setBackground(new Color(25, 35, 45));
    txtUser.setForeground(Color.WHITE);

    passPassword.setBackground(new Color(25, 35, 45));
    passPassword.setForeground(Color.WHITE);

    btnAccept.setBackground(new Color(59, 130, 246));
    btnAccept.setForeground(Color.WHITE);
    btnAccept.setFocusPainted(false);

    lblErrorMessage.setForeground(Color.LIGHT_GRAY);

    URL url = getClass().getResource("/ec/edu/espe/crealtivastudios/images/login.png");
    if (url != null) {
        ImageIcon icon = new ImageIcon(url);
        Image img = icon.getImage();
        Image scaled = img.getScaledInstance(
            lblwelcome.getWidth(),
            lblwelcome.getHeight(),
            Image.SCALE_SMOOTH
        );
        lblwelcome.setIcon(new ImageIcon(scaled));
        lblwelcome.setText("");
    }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAccept = new javax.swing.JButton();
        txtUser = new javax.swing.JTextField();
        passPassword = new javax.swing.JPasswordField();
        lblwelcome = new javax.swing.JLabel();
        lblErrorMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REGISTRO");

        btnAccept.setText("Empezar");
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });

        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });

        passPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passPasswordFocusGained(evt);
            }
        });
        passPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passPasswordMouseClicked(evt);
            }
        });
        passPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passPasswordActionPerformed(evt);
            }
        });

        lblwelcome.setText("LogoWelcome");

        lblErrorMessage.setText(".");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblwelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAccept)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtUser)
                        .addComponent(passPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                    .addComponent(lblErrorMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lblErrorMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnAccept)
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblwelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed

        String userName= txtUser.getText();
        String pasword = passPassword.getText();

        User user=new User(userName,pasword,"family");
        if ( UserController.validateLogin(user)) {
            FrmCrealtivaStudiosMenu frmCrealtivaStudiosMenu = new FrmCrealtivaStudiosMenu();
            frmCrealtivaStudiosMenu.setVisible(true);
            lblErrorMessage.setForeground(Color.black);
            lblErrorMessage.setText("Bienvenido");
            this.setVisible(false);

        }else {
            lblErrorMessage.setForeground(Color.red);
            lblErrorMessage.setText("La clave o el usuario son incorrectos");
        }

    }//GEN-LAST:event_btnAcceptActionPerformed

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserActionPerformed

    private void passPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passPasswordFocusGained
        passPassword.setText("");
    }//GEN-LAST:event_passPasswordFocusGained

    private void passPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passPasswordMouseClicked

        passPassword.setText("");

    }//GEN-LAST:event_passPasswordMouseClicked

    private void passPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passPasswordActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_passPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      

    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (Exception ex) {
        logger.log(java.util.logging.Level.SEVERE, null, ex);
    }

    java.awt.EventQueue.invokeLater(() -> new FrmCrealtivaStudiosLogin().setVisible(true));
 }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccept;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblErrorMessage;
    private javax.swing.JLabel lblwelcome;
    private javax.swing.JPasswordField passPassword;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
