package ec.edu.espe.crealtivastudios.view;

import ec.edu.espe.crealtivastudios.controller.MenuController;
import java.awt.Image;
import javax.swing.ImageIcon;

public class FrmCrealtivaStudiosMenu extends javax.swing.JFrame {

    private final MenuController menuController = new MenuController();

    public FrmCrealtivaStudiosMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
    javax.swing.SwingUtilities.invokeLater(() -> {
            // Asegurate que jLabel1 sea el nombre de tu etiqueta en el diseño
            loadImageIntoLabel(jLabel1, "caratula.jpg"); 
        });
    }
    
    private void loadImageIntoLabel(javax.swing.JLabel label, String imageName) {
        try {
            java.net.URL url = getClass().getResource("/ec/edu/espe/crealtivastudios/images/" + imageName);
            if (url == null) {
                System.err.println("Imagen no encontrada: " + imageName);
                return;
            }
            ImageIcon icon = new ImageIcon(url);
            Image img = icon.getImage();

            int w = Math.max(1, label.getWidth());
            int h = Math.max(1, label.getHeight());

            Image scaled = img.getScaledInstance(w, h, Image.SCALE_SMOOTH);
            label.setIcon(new ImageIcon(scaled));
            label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            label.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
            label.setText("");
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuCustomer = new javax.swing.JMenu();
        mniCustomerRegister = new javax.swing.JMenuItem();
        mnuCite = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        mniVideCalls = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jReportEvent = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("picture Photographers");

        mnuCustomer.setText("Clientes");

        mniCustomerRegister.setText("Registro de clientes");
        mniCustomerRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCustomerRegisterActionPerformed(evt);
            }
        });
        mnuCustomer.add(mniCustomerRegister);

        jMenuBar1.add(mnuCustomer);

        mnuCite.setText("Citas");
        mnuCite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCiteActionPerformed(evt);
            }
        });

        jMenuItem4.setText("Eventos");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        mnuCite.add(jMenuItem4);

        mniVideCalls.setText("Videollamadas");
        mniVideCalls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniVideCallsActionPerformed(evt);
            }
        });
        mnuCite.add(mniVideCalls);

        jMenuItem5.setText("Calendario");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        mnuCite.add(jMenuItem5);

        jMenuBar1.add(mnuCite);

        jMenu4.setText("Pagos");

        jMenuItem6.setText("Factura");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem6);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Reportes");

        jReportEvent.setText("Reporte de Evento");
        jReportEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jReportEventActionPerformed(evt);
            }
        });
        jMenu5.add(jReportEvent);

        jMenuItem7.setText("Reporte del Fotografo");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem7);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Equipo");

        jMenuItem1.setText("Fotografos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem1);

        jMenuItem2.setText("Equipo Disponible");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem2);

        jMenuItem3.setText("Asistencia de Fotografos");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem3);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1006, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
menuController.openPhotographerSystem(this);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
menuController.openEquipmentSystem(this);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
menuController.openAttendanceSystem(this);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
      menuController.openCalendar(this);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
menuController.openEventSystem(this);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void mniCustomerRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCustomerRegisterActionPerformed
menuController.openCustomerSystem(this);
    }//GEN-LAST:event_mniCustomerRegisterActionPerformed

    private void mnuCiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCiteActionPerformed
       
    }//GEN-LAST:event_mnuCiteActionPerformed

    private void mniVideCallsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniVideCallsActionPerformed
menuController.openVideoCalls(this);
    }//GEN-LAST:event_mniVideCallsActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
menuController.openBillingSystem(this);      
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jReportEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jReportEventActionPerformed
menuController.openReports(this);  
    }//GEN-LAST:event_jReportEventActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        FrmReportPhotographers frmReportPhotographers = new FrmReportPhotographers();
        this.setVisible(false);
        frmReportPhotographers.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
     try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            System.err.println("UI Error: " + ex.getMessage());
        }
        
        java.awt.EventQueue.invokeLater(() -> new FrmCrealtivaStudiosMenu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jReportEvent;
    private javax.swing.JMenuItem mniCustomerRegister;
    private javax.swing.JMenuItem mniVideCalls;
    private javax.swing.JMenu mnuCite;
    private javax.swing.JMenu mnuCustomer;
    // End of variables declaration//GEN-END:variables
}
