package ec.edu.espe.crealtivastudios.view;

import ec.edu.espe.crealtivastudios.controller.MenuController;
import ec.edu.espe.crealtivastudios.controller.VideoCallController;
import ec.edu.espe.crealtivastudios.model.VideoCall;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

public class FrmVideoCalls extends javax.swing.JFrame {
    
    private final VideoCallController controller = new VideoCallController();
    private boolean isEditing = false;
    private String currentId = null;

    public FrmVideoCalls() {
        initComponents();
        this.setLocationRelativeTo(null);
        loadCustomers();
        refreshTable();
    }
    
   
    private void refreshTable() {
        tblVideoCalls.setModel(controller.getVideoCallsTableModel());
    }
    
    private void resetForm() {
        dcVideoCallDate.setDate(null);
        txtHour.setText("");
        cmbMedium.setSelectedIndex(0);
        cmbCustomers.setSelectedIndex(-1);
        isEditing = false;
        currentId = null;
        btnScheduleVideoCall.setText("Programar");
    }
    
    private String getSelectedIdRaw() {
        int row = tblVideoCalls.getSelectedRow();
        if (row == -1) return null;
        return tblVideoCalls.getValueAt(row, 0).toString();
    }
    
    private void loadCustomers() {
        cmbCustomers.removeAllItems();
        controller.customerController.getAllCustomers().forEach(c -> 
            cmbCustomers.addItem(c.getId() + " - " + c.getName())
        );
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dcVideoCallDate = new com.toedter.calendar.JDateChooser();
        txtHour = new javax.swing.JTextField();
        cmbMedium = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVideoCalls = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        cmbCustomers = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        btnScheduleVideoCall = new javax.swing.JButton();
        btnEditVideoCall = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnDeleteVideoCall = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.SystemColor.activeCaption);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Videollamadas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(337, 337, 337)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(21, 21, 21))
        );

        jLabel2.setText("Fecha:");

        jLabel3.setText("Hora:");

        jLabel4.setText("Medio:");

        txtHour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHourActionPerformed(evt);
            }
        });

        cmbMedium.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Zoom", "Meet", "Teams" }));

        tblVideoCalls.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Cliente", "Fecha y hora", "Medio"
            }
        ));
        jScrollPane1.setViewportView(tblVideoCalls);

        jLabel5.setText("Cliente:");

        cmbCustomers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dcVideoCallDate, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cmbMedium, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtHour, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cmbCustomers, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cmbCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(dcVideoCallDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cmbMedium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 87, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel3.setBackground(java.awt.SystemColor.activeCaption);
        jPanel3.setForeground(java.awt.SystemColor.activeCaption);

        btnScheduleVideoCall.setText("Programar");
        btnScheduleVideoCall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScheduleVideoCallActionPerformed(evt);
            }
        });

        btnEditVideoCall.setText("Editar ");
        btnEditVideoCall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditVideoCallActionPerformed(evt);
            }
        });

        btnExit.setText("Salir");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnDeleteVideoCall.setText("Eliminar ");
        btnDeleteVideoCall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteVideoCallActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(btnScheduleVideoCall)
                .addGap(105, 105, 105)
                .addComponent(btnEditVideoCall)
                .addGap(107, 107, 107)
                .addComponent(btnDeleteVideoCall)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExit)
                .addGap(75, 75, 75))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnScheduleVideoCall)
                    .addComponent(btnEditVideoCall)
                    .addComponent(btnExit)
                    .addComponent(btnDeleteVideoCall))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtHourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHourActionPerformed
        
    }//GEN-LAST:event_txtHourActionPerformed

    private void btnScheduleVideoCallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScheduleVideoCallActionPerformed
    String customerData = (cmbCustomers.getSelectedItem() != null) ? cmbCustomers.getSelectedItem().toString() : "";
        
        controller.saveVideoCall(
            customerData,
            cmbMedium.getSelectedItem().toString(),
            dcVideoCallDate.getDate(),
            txtHour.getText(),
            isEditing,
            () -> {
                JOptionPane.showMessageDialog(this, "Videollamada guardada correctamente.");
                refreshTable();
                resetForm();
            },
            this
        );
    }//GEN-LAST:event_btnScheduleVideoCallActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed

        new FrmCrealtivaStudiosMenu().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnDeleteVideoCallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteVideoCallActionPerformed
        String idRaw = getSelectedIdRaw();
        if (idRaw == null) { JOptionPane.showMessageDialog(this, "Seleccione una videollamada"); return; }

        int confirm = JOptionPane.showConfirmDialog(this, "¿Eliminar la videollamada?", "Confirmar", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) return;

        controller.deleteVideoCall(Integer.parseInt(idRaw), this::refreshTable, this);
    }//GEN-LAST:event_btnDeleteVideoCallActionPerformed

    private void btnEditVideoCallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditVideoCallActionPerformed
        String idRaw = getSelectedIdRaw();
        if (idRaw == null) { JOptionPane.showMessageDialog(this, "Seleccione una videollamada"); return; }

        VideoCall v = controller.getVideoCallById(Integer.parseInt(idRaw));
        if (v == null) return;

        currentId = String.valueOf(v.getId());
        try {
            dcVideoCallDate.setDate(new SimpleDateFormat("yyyy-MM-dd").parse(v.getDate()));
        } catch (Exception e) { e.printStackTrace(); }
        txtHour.setText(v.getTime());
        cmbMedium.setSelectedItem(v.getPlatform());

        for (int i = 0; i < cmbCustomers.getItemCount(); i++) {
            if (cmbCustomers.getItemAt(i).startsWith(v.getCustomerId() + " -")) {
                cmbCustomers.setSelectedIndex(i);
                break;
            }
        }

        isEditing = true;
        btnScheduleVideoCall.setText("Actualizar");
    }//GEN-LAST:event_btnEditVideoCallActionPerformed
    


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            System.err.println("UI Error: " + ex.getMessage());
        }
        
        java.awt.EventQueue.invokeLater(() -> new FrmVideoCalls().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteVideoCall;
    private javax.swing.JButton btnEditVideoCall;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnScheduleVideoCall;
    private javax.swing.JComboBox<String> cmbCustomers;
    private javax.swing.JComboBox<String> cmbMedium;
    private com.toedter.calendar.JDateChooser dcVideoCallDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblVideoCalls;
    private javax.swing.JTextField txtHour;
    // End of variables declaration//GEN-END:variables
}
