package ec.edu.espe.crealtivastudios.view;

import java.awt.Image;
import java.net.URL;
import javax.swing.ImageIcon;

/**
 *
 * @author Kevin Chalan, OBJECT MASTER, OOP
 */
public class FrmCrealtivaStudiosMenu extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmCrealtivaStudiosMenu.class.getName());

    /**
     * Creates new form FrmCrealtivaStudiosMenu
     */
    public FrmCrealtivaStudiosMenu() {
        initComponents();
        URL url = getClass().getResource("/ec/edu/espe/crealtivastudios/images/chica1.jpg");

        if (url != null) {
            ImageIcon icon = new ImageIcon(url);
            Image img = icon.getImage();

            int width = jLabel1.getWidth();
            int height = jLabel1.getHeight();

            Image scaled = img.getScaledInstance(width, height, Image.SCALE_SMOOTH);
            jLabel1.setIcon(new ImageIcon(scaled));

            jLabel1.setText("");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton2 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuCustomer = new javax.swing.JMenu();
        mniCustomerRegister = new javax.swing.JMenuItem();
        mnuCite = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        mniVideCalls = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jReportEvent = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToggleButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jToggleButton2.setText("Fotógrafos");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("picture Photographers");

        mnuCustomer.setText("Clientes");

        mniCustomerRegister.setText("Registro de clientes");
        mniCustomerRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCustomerRegisterActionPerformed(evt);
            }
        });
        mnuCustomer.add(mniCustomerRegister);

        jMenuBar1.add(mnuCustomer);

        mnuCite.setText("Citas");
        mnuCite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCiteActionPerformed(evt);
            }
        });

        jMenuItem4.setText("Eventos");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        mnuCite.add(jMenuItem4);

        mniVideCalls.setText("Videollamadas");
        mniVideCalls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniVideCallsActionPerformed(evt);
            }
        });
        mnuCite.add(mniVideCalls);

        jMenuItem5.setText("Calendario");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        mnuCite.add(jMenuItem5);

        jMenuBar1.add(mnuCite);

        jMenu4.setText("Pagos");

        jMenuItem6.setText("Factura");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem6);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Reportes");

        jReportEvent.setText("Reporte de Evento");
        jReportEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jReportEventActionPerformed(evt);
            }
        });
        jMenu5.add(jReportEvent);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Equipo");

        jMenuItem1.setText("Fotografos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem1);

        jMenuItem2.setText("Equipo Disponible");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem2);

        jMenuItem3.setText("Asistencia de Fotografos");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem3);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jToggleButton2)))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jToggleButton2)
                .addGap(68, 68, 68))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        FrmPhotographer frmPhotographer = new FrmPhotographer();
        frmPhotographer.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        FrmEquipmentAvailable frmEquipmentAvailable = new FrmEquipmentAvailable();
        frmEquipmentAvailable.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        FrmAtendencePhotographers frmAtendencePhotographers = new FrmAtendencePhotographers();
        frmAtendencePhotographers.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        FrmPhotographer frmPhotographer = new FrmPhotographer();
        frmPhotographer.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        FrmCalendar frmCalendar = new FrmCalendar();
        frmCalendar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        
        FrmEvent frmEvent = new FrmEvent();
        frmEvent.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void mniCustomerRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCustomerRegisterActionPerformed
        
        FrmCustomer frmCustomer = new FrmCustomer();
        frmCustomer.setLocationRelativeTo(null); 
        frmCustomer.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_mniCustomerRegisterActionPerformed

    private void mnuCiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCiteActionPerformed
       
    }//GEN-LAST:event_mnuCiteActionPerformed

    private void mniVideCallsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniVideCallsActionPerformed
        
        FrmVideoCalls videoCallWindow = new FrmVideoCalls();
        videoCallWindow.setVisible(true);
        videoCallWindow.setLocationRelativeTo(null);
        
        this.dispose();
        
    }//GEN-LAST:event_mniVideCallsActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
    FrmBillp frmBillp = new FrmBillp();
    frmBillp.setVisible(true);
    this.dispose();         
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jReportEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jReportEventActionPerformed
FrmReportEvent frmReportEvent = new FrmReportEvent();
frmReportEvent.setVisible(true);
this.dispose();   
    }//GEN-LAST:event_jReportEventActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmCrealtivaStudiosMenu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jReportEvent;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JMenuItem mniCustomerRegister;
    private javax.swing.JMenuItem mniVideCalls;
    private javax.swing.JMenu mnuCite;
    private javax.swing.JMenu mnuCustomer;
    // End of variables declaration//GEN-END:variables
}
